import 'package:flutter/foundation.dart';

/// Recurrence pattern for tasks
enum RecurrenceType {
  none, // One-time task
  daily,
  weekly,
  biweekly,
  monthly,
  custom, // Uses intervalDays
}

/// Task priority
enum TaskPriority { low, normal, high }

/// A task/reminder - can be auto-generated or user-created
@immutable
class Task {
  final String id;
  final String? tankId; // Null for global tasks
  final String title;
  final String? description;
  final RecurrenceType recurrence;
  final int? intervalDays; // For custom recurrence
  final DateTime? dueDate; // Next due date
  final TaskPriority priority;
  final bool isEnabled; // Can be disabled without deleting
  final bool isAutoGenerated; // System-created vs user-created
  final DateTime? lastCompletedAt;
  final int completionCount;
  final String? relatedEquipmentId; // For equipment-specific tasks
  final DateTime createdAt;
  final DateTime updatedAt;

  const Task({
    required this.id,
    this.tankId,
    required this.title,
    this.description,
    required this.recurrence,
    this.intervalDays,
    this.dueDate,
    this.priority = TaskPriority.normal,
    this.isEnabled = true,
    this.isAutoGenerated = false,
    this.lastCompletedAt,
    this.completionCount = 0,
    this.relatedEquipmentId,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Is the task overdue?
  bool get isOverdue {
    if (dueDate == null || !isEnabled) return false;
    return DateTime.now().isAfter(dueDate!);
  }

  /// Is the task due today?
  bool get isDueToday {
    if (dueDate == null || !isEnabled) return false;
    final now = DateTime.now();
    return dueDate!.year == now.year &&
        dueDate!.month == now.month &&
        dueDate!.day == now.day;
  }

  /// Days until due (negative if overdue)
  int? get daysUntilDue {
    if (dueDate == null) return null;
    final now = DateTime.now();
    final todayStart = DateTime(now.year, now.month, now.day);
    final dueStart = DateTime(dueDate!.year, dueDate!.month, dueDate!.day);
    return dueStart.difference(todayStart).inDays;
  }

  /// Calculate next due date after completion
  /// Uses the current dueDate as the base if available, otherwise uses now
  /// This prevents "losing time" if a task is completed late
  DateTime? calculateNextDueDate() {
    final baseDate = dueDate ?? DateTime.now();
    switch (recurrence) {
      case RecurrenceType.none:
        return null;
      case RecurrenceType.daily:
        return baseDate.add(const Duration(days: 1));
      case RecurrenceType.weekly:
        return baseDate.add(const Duration(days: 7));
      case RecurrenceType.biweekly:
        return baseDate.add(const Duration(days: 14));
      case RecurrenceType.monthly:
        return _calculateNextMonthDate(baseDate);
      case RecurrenceType.custom:
        if (intervalDays != null) {
          return baseDate.add(Duration(days: intervalDays!));
        }
        return null;
    }
  }

  /// Safely calculate next month's date, clamping day to valid range
  /// Handles edge cases like Jan 31 → Feb 28/29, May 31 → Jun 30, etc.
  DateTime _calculateNextMonthDate(DateTime current) {
    int targetYear = current.year;
    int targetMonth = current.month + 1;

    // Handle year rollover
    if (targetMonth > 12) {
      targetMonth = 1;
      targetYear++;
    }

    // Clamp day to valid range for target month
    final daysInTargetMonth = _getDaysInMonth(targetYear, targetMonth);
    final targetDay = current.day > daysInTargetMonth
        ? daysInTargetMonth
        : current.day;

    return DateTime(targetYear, targetMonth, targetDay);
  }

  /// Get the number of days in a given month/year
  /// Handles leap years correctly
  int _getDaysInMonth(int year, int month) {
    // Month is 1-indexed (1 = January, 12 = December)
    switch (month) {
      case 1: // January
      case 3: // March
      case 5: // May
      case 7: // July
      case 8: // August
      case 10: // October
      case 12: // December
        return 31;
      case 4: // April
      case 6: // June
      case 9: // September
      case 11: // November
        return 30;
      case 2: // February
        return _isLeapYear(year) ? 29 : 28;
      default:
        throw ArgumentError('Invalid month: $month');
    }
  }

  /// Check if a year is a leap year
  bool _isLeapYear(int year) {
    // Leap year if divisible by 4, except century years must be divisible by 400
    if (year % 400 == 0) return true;
    if (year % 100 == 0) return false;
    return year % 4 == 0;
  }

  factory Task.fromJson(Map<String, dynamic> json) {
    return Task(
      id: json['id'] as String,
      tankId: json['tankId'] as String?,
      title: json['title'] as String,
      description: json['description'] as String?,
      recurrence: RecurrenceType.values.firstWhere(
        (e) => e.name == json['recurrence'],
        orElse: () => RecurrenceType.none,
      ),
      intervalDays: json['intervalDays'] as int?,
      dueDate: json['dueDate'] != null
          ? DateTime.parse(json['dueDate'] as String)
          : null,
      priority: TaskPriority.values.firstWhere(
        (e) => e.name == (json['priority'] ?? 'normal'),
        orElse: () => TaskPriority.normal,
      ),
      isEnabled: json['isEnabled'] as bool? ?? true,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      lastCompletedAt: json['lastCompletedAt'] != null
          ? DateTime.parse(json['lastCompletedAt'] as String)
          : null,
      completionCount: json['completionCount'] as int? ?? 0,
      relatedEquipmentId: json['relatedEquipmentId'] as String?,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'tankId': tankId,
      'title': title,
      'description': description,
      'recurrence': recurrence.name,
      'intervalDays': intervalDays,
      'dueDate': dueDate?.toIso8601String(),
      'priority': priority.name,
      'isEnabled': isEnabled,
      'isAutoGenerated': isAutoGenerated,
      'lastCompletedAt': lastCompletedAt?.toIso8601String(),
      'completionCount': completionCount,
      'relatedEquipmentId': relatedEquipmentId,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  /// Complete the task and get updated version
  Task complete() {
    final now = DateTime.now();
    final nextDue = calculateNextDueDate();

    // For one-time tasks (none recurrence), explicitly set dueDate to null
    if (recurrence == RecurrenceType.none) {
      return Task(
        id: id,
        tankId: tankId,
        title: title,
        description: description,
        recurrence: recurrence,
        intervalDays: intervalDays,
        dueDate: null, // Explicitly null for one-time tasks
        priority: priority,
        isEnabled: isEnabled,
        isAutoGenerated: isAutoGenerated,
        lastCompletedAt: now,
        completionCount: completionCount + 1,
        relatedEquipmentId: relatedEquipmentId,
        createdAt: createdAt,
        updatedAt: now,
      );
    }

    return copyWith(
      lastCompletedAt: now,
      completionCount: completionCount + 1,
      dueDate: nextDue,
      updatedAt: now,
    );
  }

  /// Snooze the task by a number of days
  Task snooze(int days) {
    final now = DateTime.now();
    return copyWith(
      dueDate: now.add(Duration(days: days)),
      updatedAt: now,
    );
  }

  Task copyWith({
    String? id,
    String? tankId,
    String? title,
    String? description,
    RecurrenceType? recurrence,
    int? intervalDays,
    DateTime? dueDate,
    TaskPriority? priority,
    bool? isEnabled,
    bool? isAutoGenerated,
    DateTime? lastCompletedAt,
    int? completionCount,
    String? relatedEquipmentId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Task(
      id: id ?? this.id,
      tankId: tankId ?? this.tankId,
      title: title ?? this.title,
      description: description ?? this.description,
      recurrence: recurrence ?? this.recurrence,
      intervalDays: intervalDays ?? this.intervalDays,
      dueDate: dueDate ?? this.dueDate,
      priority: priority ?? this.priority,
      isEnabled: isEnabled ?? this.isEnabled,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      lastCompletedAt: lastCompletedAt ?? this.lastCompletedAt,
      completionCount: completionCount ?? this.completionCount,
      relatedEquipmentId: relatedEquipmentId ?? this.relatedEquipmentId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

/// Factory for creating default tasks for a new tank
class DefaultTasks {
  static List<Task> forNewTank(String tankId) {
    final now = DateTime.now();
    return [
      Task(
        id: '${tankId}_water_change',
        tankId: tankId,
        title: 'Weekly Water Change',
        description: 'Change 20-30% of tank water',
        recurrence: RecurrenceType.weekly,
        dueDate: now.add(const Duration(days: 7)),
        priority: TaskPriority.high,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      Task(
        id: '${tankId}_water_test',
        tankId: tankId,
        title: 'Water Test',
        description: 'Test ammonia, nitrite, nitrate, pH',
        recurrence: RecurrenceType.weekly,
        dueDate: now.add(const Duration(days: 7)),
        priority: TaskPriority.normal,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      Task(
        id: '${tankId}_glass_clean',
        tankId: tankId,
        title: 'Clean Glass',
        description: 'Scrape algae from glass if needed',
        recurrence: RecurrenceType.weekly,
        dueDate: now.add(const Duration(days: 7)),
        priority: TaskPriority.low,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      Task(
        id: '${tankId}_filter_check',
        tankId: tankId,
        title: 'Filter Maintenance',
        description: 'Rinse filter media in tank water, check flow',
        recurrence: RecurrenceType.monthly,
        dueDate: now.add(const Duration(days: 30)),
        priority: TaskPriority.normal,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }
}
