/// Recurrence pattern for tasks
enum RecurrenceType {
  none, // One-time task
  daily,
  weekly,
  biweekly,
  monthly,
  custom, // Uses intervalDays
}

/// Task priority
enum TaskPriority {
  low,
  normal,
  high,
}

/// A task/reminder — can be auto-generated or user-created
class Task {
  final String id;
  final String? tankId; // Null for global tasks
  final String title;
  final String? description;
  final RecurrenceType recurrence;
  final int? intervalDays; // For custom recurrence
  final DateTime? dueDate; // Next due date
  final TaskPriority priority;
  final bool isEnabled; // Can be disabled without deleting
  final bool isAutoGenerated; // System-created vs user-created
  final DateTime? lastCompletedAt;
  final int completionCount;
  final String? relatedEquipmentId; // For equipment-specific tasks
  final DateTime createdAt;
  final DateTime updatedAt;

  Task({
    required this.id,
    this.tankId,
    required this.title,
    this.description,
    required this.recurrence,
    this.intervalDays,
    this.dueDate,
    this.priority = TaskPriority.normal,
    this.isEnabled = true,
    this.isAutoGenerated = false,
    this.lastCompletedAt,
    this.completionCount = 0,
    this.relatedEquipmentId,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Is the task overdue?
  bool get isOverdue {
    if (dueDate == null || !isEnabled) return false;
    return DateTime.now().isAfter(dueDate!);
  }

  /// Is the task due today?
  bool get isDueToday {
    if (dueDate == null || !isEnabled) return false;
    final now = DateTime.now();
    return dueDate!.year == now.year &&
        dueDate!.month == now.month &&
        dueDate!.day == now.day;
  }

  /// Days until due (negative if overdue)
  int? get daysUntilDue {
    if (dueDate == null) return null;
    final now = DateTime.now();
    final todayStart = DateTime(now.year, now.month, now.day);
    final dueStart = DateTime(dueDate!.year, dueDate!.month, dueDate!.day);
    return dueStart.difference(todayStart).inDays;
  }

  /// Calculate next due date after completion
  DateTime? calculateNextDueDate() {
    final now = DateTime.now();
    switch (recurrence) {
      case RecurrenceType.none:
        return null;
      case RecurrenceType.daily:
        return now.add(const Duration(days: 1));
      case RecurrenceType.weekly:
        return now.add(const Duration(days: 7));
      case RecurrenceType.biweekly:
        return now.add(const Duration(days: 14));
      case RecurrenceType.monthly:
        return DateTime(now.year, now.month + 1, now.day);
      case RecurrenceType.custom:
        if (intervalDays != null) {
          return now.add(Duration(days: intervalDays!));
        }
        return null;
    }
  }

  /// Complete the task and get updated version
  Task complete() {
    final now = DateTime.now();
    return copyWith(
      lastCompletedAt: now,
      completionCount: completionCount + 1,
      dueDate: calculateNextDueDate(),
      updatedAt: now,
    );
  }

  /// Snooze the task by a number of days
  Task snooze(int days) {
    final now = DateTime.now();
    return copyWith(
      dueDate: now.add(Duration(days: days)),
      updatedAt: now,
    );
  }

  Task copyWith({
    String? id,
    String? tankId,
    String? title,
    String? description,
    RecurrenceType? recurrence,
    int? intervalDays,
    DateTime? dueDate,
    TaskPriority? priority,
    bool? isEnabled,
    bool? isAutoGenerated,
    DateTime? lastCompletedAt,
    int? completionCount,
    String? relatedEquipmentId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Task(
      id: id ?? this.id,
      tankId: tankId ?? this.tankId,
      title: title ?? this.title,
      description: description ?? this.description,
      recurrence: recurrence ?? this.recurrence,
      intervalDays: intervalDays ?? this.intervalDays,
      dueDate: dueDate ?? this.dueDate,
      priority: priority ?? this.priority,
      isEnabled: isEnabled ?? this.isEnabled,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      lastCompletedAt: lastCompletedAt ?? this.lastCompletedAt,
      completionCount: completionCount ?? this.completionCount,
      relatedEquipmentId: relatedEquipmentId ?? this.relatedEquipmentId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

/// Factory for creating default tasks for a new tank
class DefaultTasks {
  static List<Task> forNewTank(String tankId) {
    final now = DateTime.now();
    return [
      Task(
        id: '${tankId}_water_change',
        tankId: tankId,
        title: 'Weekly Water Change',
        description: 'Change 20-30% of tank water',
        recurrence: RecurrenceType.weekly,
        dueDate: now.add(const Duration(days: 7)),
        priority: TaskPriority.high,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      Task(
        id: '${tankId}_water_test',
        tankId: tankId,
        title: 'Water Test',
        description: 'Test ammonia, nitrite, nitrate, pH',
        recurrence: RecurrenceType.weekly,
        dueDate: now.add(const Duration(days: 7)),
        priority: TaskPriority.normal,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      Task(
        id: '${tankId}_glass_clean',
        tankId: tankId,
        title: 'Clean Glass',
        description: 'Scrape algae from glass if needed',
        recurrence: RecurrenceType.weekly,
        dueDate: now.add(const Duration(days: 7)),
        priority: TaskPriority.low,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      Task(
        id: '${tankId}_filter_check',
        tankId: tankId,
        title: 'Filter Maintenance',
        description: 'Rinse filter media in tank water, check flow',
        recurrence: RecurrenceType.monthly,
        dueDate: now.add(const Duration(days: 30)),
        priority: TaskPriority.normal,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }
}
