import 'package:flutter/material.dart';
import 'package:skeletonizer/skeletonizer.dart';
import '../widgets/core/bubble_loader.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import '../models/models.dart';
import '../providers/storage_provider.dart';
import '../providers/tank_provider.dart';
import '../providers/user_profile_provider.dart';
import '../providers/inventory_provider.dart';
import '../services/storage_service.dart';
import '../services/xp_animation_service.dart';
import '../theme/app_theme.dart';
import '../utils/app_feedback.dart';
import '../utils/skeleton_placeholders.dart';
import '../widgets/core/app_card.dart';
import '../widgets/empty_state.dart';
import '../widgets/error_state.dart';
import '../widgets/mascot/mascot_widgets.dart';

const _uuid = Uuid();

String _maintenanceTaskId(String equipmentId) =>
    'equip_${equipmentId}_maintenance';

/// Ensure an auto-generated maintenance task exists (or is removed) based on equipment interval.
Future<void> _syncEquipmentMaintenanceTask(
  StorageService storage,
  Equipment equipment,
) async {
  final interval = equipment.maintenanceIntervalDays;
  final taskId = _maintenanceTaskId(equipment.id);

  if (interval == null || interval <= 0) {
    // No schedule → remove the auto task if present.
    await storage.deleteTask(taskId);
    return;
  }

  final now = DateTime.now();
  final baseDate = equipment.lastServiced ?? now;
  final due = baseDate.add(Duration(days: interval));

  final tasks = await storage.getTasksForTank(equipment.tankId);
  Task? existing;
  for (final t in tasks) {
    if (t.id == taskId) {
      existing = t;
      break;
    }
  }

  final title = 'Service ${equipment.name}';
  final description =
      'Maintenance for ${equipment.typeName}${equipment.brand != null ? ' (${equipment.brand})' : ''}';

  final task =
      (existing ??
              Task(
                id: taskId,
                tankId: equipment.tankId,
                title: title,
                description: description,
                recurrence: RecurrenceType.custom,
                intervalDays: interval,
                dueDate: due,
                priority: TaskPriority.normal,
                isEnabled: true,
                isAutoGenerated: true,
                lastCompletedAt: null,
                completionCount: 0,
                relatedEquipmentId: equipment.id,
                createdAt: now,
                updatedAt: now,
              ))
          .copyWith(
            title: title,
            description: description,
            recurrence: RecurrenceType.custom,
            intervalDays: interval,
            dueDate: due,
            isAutoGenerated: true,
            relatedEquipmentId: equipment.id,
            updatedAt: now,
          );

  await storage.saveTask(task);
}

class EquipmentScreen extends ConsumerWidget {
  final String tankId;

  const EquipmentScreen({super.key, required this.tankId});

  Widget _buildSkeletonList() {
    final placeholders = SkeletonPlaceholders.equipmentList;
    return Skeletonizer(
      child: ListView.builder(
        padding: const EdgeInsets.all(AppSpacing.md),
        itemCount: placeholders.length,
        itemBuilder: (context, index) {
          final equipment = placeholders[index];
          return _EquipmentCard(
            equipment: equipment,
            onEdit: () {},
            onService: () {},
            onHistory: () {},
            onDelete: () {},
          );
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final equipmentAsync = ref.watch(equipmentProvider(tankId));

    return Scaffold(
      appBar: AppBar(title: const Text('Equipment')),
      body: equipmentAsync.when(
        loading: () => _buildSkeletonList(),
        error: (err, _) => ErrorState(
          message: 'Failed to load equipment',
          details: 'Please check your connection and try again.',
          onRetry: () => ref.invalidate(equipmentProvider(tankId)),
        ),
        data: (equipment) {
          if (equipment.isEmpty) {
            return EmptyState.withMascot(
              icon: Icons.settings,
              title: 'No equipment yet',
              message: 'Add your filters, heaters, lights, and other gear to track maintenance schedules',
              mascotContext: MascotContext.noEquipment,
              actionLabel: 'Add Equipment',
              onAction: () => _showAddDialog(context, ref),
              tips: const [
                'Track filter maintenance to keep water clean',
                'Set reminders for heater checks',
                'Monitor light schedules for plant health',
              ],
            );
          }

          final overdue = equipment.where((e) => e.isMaintenanceOverdue).length;

          return RefreshIndicator(
            onRefresh: () async {
              ref.invalidate(equipmentProvider(tankId));
              await Future.delayed(const Duration(milliseconds: 500));
            },
            child: ListView.builder(
              padding: const EdgeInsets.all(AppSpacing.md),
              itemCount: equipment.length + (overdue > 0 ? 2 : 0), // +2 for warning card and spacing if overdue
              itemBuilder: (context, index) {
                // Summary card
                if (overdue > 0 && index == 0) {
                  return AppCard(
                    backgroundColor: AppOverlays.warning10,
                    padding: AppCardPadding.standard,
                    child: Row(
                      children: [
                        Icon(
                          Icons.warning_amber,
                          color: AppColors.warning,
                          size: 32,
                        ),
                        const SizedBox(width: AppSpacing.md),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                '$overdue maintenance overdue',
                                style: AppTypography.labelLarge,
                              ),
                              Text(
                                'Check equipment below',
                                style: AppTypography.bodySmall,
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  );
                } else if (overdue > 0 && index == 1) {
                  return const SizedBox(height: AppSpacing.md);
                } else {
                  // List with staggered animation
                  final equipmentIndex = overdue > 0 ? index - 2 : index;
                  final e = equipment[equipmentIndex];
                  return _EquipmentCard(
                    equipment: e,
                    onEdit: () => _showEditDialog(context, ref, e),
                    onService: () => _markServiced(context, ref, e),
                    onHistory: () => _showEquipmentHistoryDialog(context, e),
                    onDelete: () => _confirmDelete(context, ref, e),
                  )
                      .animate()
                      .fadeIn(delay: (50 * equipmentIndex).ms, duration: 300.ms)
                      .slideX(begin: 0.1, end: 0, delay: (50 * equipmentIndex).ms, duration: 300.ms);
                }
              },
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddDialog(context, ref),
        tooltip: 'Add equipment',
        child: const Icon(Icons.add),
      ),
    );
  }

  void _showAddDialog(BuildContext context, WidgetRef ref) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (_) => _AddEquipmentSheet(tankId: tankId, ref: ref),
    );
  }

  void _showEditDialog(
    BuildContext context,
    WidgetRef ref,
    Equipment equipment,
  ) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (_) =>
          _AddEquipmentSheet(tankId: tankId, ref: ref, existing: equipment),
    );
  }

  Future<void> _markServiced(
    BuildContext context,
    WidgetRef ref,
    Equipment equipment,
  ) async {
    final storage = ref.read(storageServiceProvider);
    final now = DateTime.now();

    final updated = equipment.copyWith(lastServiced: now, updatedAt: now);
    await storage.saveEquipment(updated);

    // Log the maintenance event.
    await storage.saveLog(
      LogEntry(
        id: _uuid.v4(),
        tankId: tankId,
        type: LogType.equipmentMaintenance,
        timestamp: now,
        title: 'Serviced ${equipment.name}',
        notes: equipment.typeName,
        relatedEquipmentId: equipment.id,
        createdAt: now,
      ),
    );

    // Keep the auto maintenance task in sync and mark it completed.
    await _syncEquipmentMaintenanceTask(storage, updated);
    final tasks = await storage.getTasksForTank(tankId);
    final taskId = _maintenanceTaskId(equipment.id);
    Task? maintenanceTask;
    for (final t in tasks) {
      if (t.id == taskId) {
        maintenanceTask = t;
        break;
      }
    }

    if (maintenanceTask != null) {
      final completedTask = maintenanceTask.complete().copyWith(updatedAt: now);
      await storage.saveTask(completedTask);

      await storage.saveLog(
        LogEntry(
          id: _uuid.v4(),
          tankId: tankId,
          type: LogType.taskCompleted,
          timestamp: now,
          title: maintenanceTask.title,
          notes: maintenanceTask.description,
          relatedTaskId: maintenanceTask.id,
          relatedEquipmentId: equipment.id,
          createdAt: now,
        ),
      );
    }

    ref.invalidate(equipmentProvider(tankId));
    ref.invalidate(tasksProvider(tankId));
    ref.invalidate(logsProvider(tankId));
    ref.invalidate(allLogsProvider(tankId));

    if (context.mounted) {
      AppFeedback.showSuccess(context, '${equipment.name} marked as serviced');
    }
  }

  void _confirmDelete(
    BuildContext context,
    WidgetRef ref,
    Equipment equipment,
  ) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Remove Equipment?'),
        content: Text('Remove ${equipment.name}?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () async {
              Navigator.pop(ctx);
              final storage = ref.read(storageServiceProvider);
              await storage.deleteEquipment(equipment.id);
              // Remove auto maintenance task (if any)
              await storage.deleteTask(_maintenanceTaskId(equipment.id));
              ref.invalidate(equipmentProvider(tankId));
              ref.invalidate(tasksProvider(tankId));
            },
            child: const Text(
              'Remove',
              style: TextStyle(color: AppColors.error),
            ),
          ),
        ],
      ),
    );
  }

  void _showEquipmentHistoryDialog(BuildContext context, Equipment equipment) {
    showDialog(
      context: context,
      builder: (_) =>
          _EquipmentHistoryDialog(tankId: tankId, equipment: equipment),
    );
  }
}

class _EquipmentHistoryDialog extends ConsumerWidget {
  final String tankId;
  final Equipment equipment;

  const _EquipmentHistoryDialog({
    required this.tankId,
    required this.equipment,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final logsAsync = ref.watch(allLogsProvider(tankId));

    return AlertDialog(
      title: Text('History — ${equipment.name}'),
      content: SizedBox(
        width: double.maxFinite,
        child: logsAsync.when(
          loading: () => const Padding(
            padding: EdgeInsets.all(12),
            child: Center(child: CircularProgressIndicator()),
          ),
          error: (err, _) => Text('Error loading history: $err'),
          data: (logs) {
            final maintenance =
                logs
                    .where((l) => l.type == LogType.equipmentMaintenance)
                    .where((l) => l.relatedEquipmentId == equipment.id)
                    .toList()
                  ..sort((a, b) => b.timestamp.compareTo(a.timestamp));

            if (maintenance.isEmpty) {
              return Text(
                'No maintenance logs yet.\n\nTip: use “Mark Serviced” and it will show up here and in Recent Activity.',
                style: AppTypography.bodyMedium,
              );
            }

            return SizedBox(
              height: 320,
              child: ListView.separated(
                itemCount: maintenance.length.clamp(0, 25),
                separatorBuilder: (_, __) => const Divider(height: 1),
                itemBuilder: (context, i) {
                  final log = maintenance[i];
                  return ListTile(
                    contentPadding: EdgeInsets.zero,
                    leading: const Icon(
                      Icons.build_circle,
                      color: AppColors.success,
                      size: 18,
                    ),
                    title: Text(
                      DateFormat('MMM d, yyyy').format(log.timestamp),
                    ),
                    subtitle: Text(DateFormat('h:mm a').format(log.timestamp)),
                  );
                },
              ),
            );
          },
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Close'),
        ),
      ],
    );
  }
}

class _EquipmentCard extends StatelessWidget {
  final Equipment equipment;
  final VoidCallback onEdit;
  final VoidCallback onService;
  final VoidCallback onHistory;
  final VoidCallback onDelete;

  const _EquipmentCard({
    required this.equipment,
    required this.onEdit,
    required this.onService,
    required this.onHistory,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final isOverdue = equipment.isMaintenanceOverdue;
    final daysUntil = equipment.daysUntilMaintenance;

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      color: isOverdue ? AppColors.warningAlpha05 : null,
      child: Column(
        children: [
          ListTile(
            leading: CircleAvatar(
              backgroundColor: isOverdue
                  ? AppColors.warningAlpha20
                  : AppOverlays.primary10,
              child: Icon(
                _getIcon(equipment.type),
                color: isOverdue ? AppColors.warning : AppColors.primary,
              ),
            ),
            title: Text(equipment.name),
            subtitle: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(equipment.typeName, style: AppTypography.bodySmall),
                if (equipment.maintenanceIntervalDays != null) ...[
                  const SizedBox(height: AppSpacing.xs),
                  Text(
                    daysUntil != null
                        ? (daysUntil < 0
                              ? '${-daysUntil}d overdue'
                              : (daysUntil == 0
                                    ? 'Due today'
                                    : 'Due in ${daysUntil}d'))
                        : 'Service every ${equipment.maintenanceIntervalDays}d',
                    style: TextStyle(
                      color: isOverdue
                          ? AppColors.warning
                          : AppColors.textSecondary,
                      fontWeight: isOverdue
                          ? FontWeight.w500
                          : FontWeight.normal,
                    ),
                  ),
                ],
              ],
            ),
            trailing: PopupMenuButton(
              itemBuilder: (_) => [
                if (equipment.maintenanceIntervalDays != null)
                  const PopupMenuItem(
                    value: 'service',
                    child: Text('Mark Serviced'),
                  ),
                const PopupMenuItem(value: 'history', child: Text('History')),
                const PopupMenuItem(value: 'edit', child: Text('Edit')),
                const PopupMenuItem(value: 'delete', child: Text('Remove')),
              ],
              onSelected: (value) {
                if (value == 'service') onService();
                if (value == 'history') onHistory();
                if (value == 'edit') onEdit();
                if (value == 'delete') onDelete();
              },
            ),
            onTap: onEdit,
          ),
          if (equipment.lastServiced != null)
            Padding(
              padding: const EdgeInsets.only(left: 72, right: 16, bottom: 12),
              child: Row(
                children: [
                  Icon(Icons.history, size: 14, color: AppColors.textHint),
                  const SizedBox(width: AppSpacing.xs),
                  Text(
                    'Last serviced ${DateFormat('MMM d').format(equipment.lastServiced!)}',
                    style: AppTypography.bodySmall,
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  IconData _getIcon(EquipmentType type) {
    switch (type) {
      case EquipmentType.filter:
        return Icons.filter_alt;
      case EquipmentType.heater:
        return Icons.thermostat;
      case EquipmentType.light:
        return Icons.light_mode;
      case EquipmentType.airPump:
        return Icons.air;
      case EquipmentType.co2System:
        return Icons.bubble_chart;
      case EquipmentType.autoFeeder:
        return Icons.restaurant;
      case EquipmentType.thermometer:
        return Icons.device_thermostat;
      case EquipmentType.wavemaker:
        return Icons.waves;
      case EquipmentType.skimmer:
        return Icons.filter_drama;
      case EquipmentType.other:
        return Icons.settings;
    }
  }
}

class _AddEquipmentSheet extends StatefulWidget {
  final String tankId;
  final WidgetRef ref;
  final Equipment? existing;

  const _AddEquipmentSheet({
    required this.tankId,
    required this.ref,
    this.existing,
  });

  @override
  State<_AddEquipmentSheet> createState() => _AddEquipmentSheetState();
}

class _AddEquipmentSheetState extends State<_AddEquipmentSheet> {
  late TextEditingController _nameController;
  late TextEditingController _brandController;
  late TextEditingController _intervalController;
  late EquipmentType _type;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.existing?.name ?? '');
    _brandController = TextEditingController(
      text: widget.existing?.brand ?? '',
    );
    _intervalController = TextEditingController(
      text: widget.existing?.maintenanceIntervalDays?.toString() ?? '',
    );
    _type = widget.existing?.type ?? EquipmentType.filter;
  }

  @override
  void dispose() {
    _nameController.dispose();
    _brandController.dispose();
    _intervalController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FocusTraversalGroup(
      policy: OrderedTraversalPolicy(),
      child: Padding(
        padding: EdgeInsets.only(
          left: 16,
          right: 16,
          top: 16,
          bottom: MediaQuery.of(context).viewInsets.bottom + 16,
        ),
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
            Text(
              widget.existing != null ? 'Edit Equipment' : 'Add Equipment',
              style: AppTypography.headlineMedium,
            ),
            const SizedBox(height: AppSpacing.md),

            // Type selector
            Text('Type', style: AppTypography.labelLarge),
            const SizedBox(height: AppSpacing.sm),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: EquipmentType.values.map((type) {
                final isSelected = _type == type;
                return ChoiceChip(
                  label: Text(_getTypeName(type)),
                  selected: isSelected,
                  onSelected: (_) => setState(() => _type = type),
                );
              }).toList(),
            ),

            const SizedBox(height: AppSpacing.md),
            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(
                labelText: 'Name *',
                hintText: 'e.g., Fluval 307',
              ),
              textCapitalization: TextCapitalization.words,
            ),
            const SizedBox(height: 12),
            TextFormField(
              controller: _brandController,
              decoration: const InputDecoration(
                labelText: 'Brand (optional)',
                hintText: 'e.g., Fluval',
              ),
              textCapitalization: TextCapitalization.words,
            ),
            const SizedBox(height: 12),
            TextFormField(
              controller: _intervalController,
              decoration: const InputDecoration(
                labelText: 'Maintenance interval (days)',
                hintText: 'e.g., 30',
                suffixText: 'days',
              ),
              keyboardType: TextInputType.number,
              inputFormatters: [FilteringTextInputFormatter.digitsOnly],
            ),

            const SizedBox(height: AppSpacing.lg),
            ElevatedButton(
              onPressed: _isSaving ? null : _save,
              child: _isSaving
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : Text(widget.existing != null ? 'Save' : 'Add'),
            ),
          ],
        ),
      ),
      ),
    );
  }

  String _getTypeName(EquipmentType type) {
    switch (type) {
      case EquipmentType.filter:
        return 'Filter';
      case EquipmentType.heater:
        return 'Heater';
      case EquipmentType.light:
        return 'Light';
      case EquipmentType.airPump:
        return 'Air Pump';
      case EquipmentType.co2System:
        return 'CO₂';
      case EquipmentType.autoFeeder:
        return 'Feeder';
      case EquipmentType.thermometer:
        return 'Thermo';
      case EquipmentType.wavemaker:
        return 'Wave';
      case EquipmentType.skimmer:
        return 'Skimmer';
      case EquipmentType.other:
        return 'Other';
    }
  }

  Future<void> _save() async {
    final name = _nameController.text.trim();
    if (name.isEmpty) {
      AppFeedback.showWarning(context, 'Please enter a name');
      return;
    }

    setState(() => _isSaving = true);

    try {
      final storage = widget.ref.read(storageServiceProvider);
      final now = DateTime.now();
      final interval = int.tryParse(_intervalController.text);

      final equipment = Equipment(
        id: widget.existing?.id ?? _uuid.v4(),
        tankId: widget.tankId,
        type: _type,
        name: name,
        brand: _brandController.text.trim().isNotEmpty
            ? _brandController.text.trim()
            : null,
        maintenanceIntervalDays: interval,
        lastServiced:
            widget.existing?.lastServiced ?? (interval != null ? now : null),
        installedDate: widget.existing?.installedDate ?? now,
        createdAt: widget.existing?.createdAt ?? now,
        updatedAt: now,
      );

      await storage.saveEquipment(equipment);

      // Create/update (or remove) the auto maintenance task.
      await _syncEquipmentMaintenanceTask(storage, equipment);

      // Award XP for adding new equipment (not editing)
      if (widget.existing == null) {
        final isBoostActive = widget.ref.read(xpBoostActiveProvider);
        final effectiveXp = isBoostActive ? XpRewards.addEquipment * 2 : XpRewards.addEquipment;
        await widget.ref
            .read(userProfileProvider.notifier)
            .recordActivity(xp: XpRewards.addEquipment, xpBoostActive: isBoostActive);
        
        // Show XP animation
        if (mounted) {
          widget.ref.showXpAnimation(effectiveXp);
        }
      }

      widget.ref.invalidate(equipmentProvider(widget.tankId));
      widget.ref.invalidate(tasksProvider(widget.tankId));

      if (mounted) Navigator.pop(context);
    } catch (e) {
      if (mounted) {
        AppFeedback.showError(context, 'Error: $e');
      }
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }
}
